"""
reporter.py -- Generate data quality reports in Markdown and HTML.

Consumes a list of ``DQResult`` objects from ``data_quality.py`` and
produces:
    - A Markdown report suitable for version control or static hosting.
    - An HTML report rendered via Jinja2 for stakeholder distribution.

Reports are written to the directory configured by ``FDM_REPORT_DIR``
(default ``reports/``).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Template

from src import REPORT_DIR, ensure_dirs
from src.data_quality import DQResult

# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

_MD_TEMPLATE = """\
# Data Quality Report

**Generated:** {{ timestamp }}
**Database:** {{ db_path }}
**Total Checks:** {{ total }}
**Passed:** {{ passed }} | **Failed:** {{ failed }}
**Overall Pass Rate:** {{ pass_rate }}%

---

## Summary

| # | Check ID | Dimension | Name | Result | Affected Rows | Total Rows | Pass Rate |
|---|----------|-----------|------|--------|---------------|------------|-----------|
{% for r in results -%}
| {{ loop.index }} | {{ r.check_id }} | {{ r.dimension }} | {{ r.name }} | {{ "PASS" if r.passed else "FAIL" }} | {{ r.affected_rows }} | {{ r.total_rows }} | {{ "%.2f"|format(r.pass_rate * 100) }}% |
{% endfor %}

---

## Detailed Results

{% for r in results %}
### {{ r.check_id }}: {{ r.name }}

- **Dimension:** {{ r.dimension }}
- **Description:** {{ r.description }}
- **Result:** {{ "PASS" if r.passed else "FAIL" }}
- **Details:** {{ r.details }}
- **Affected Rows:** {{ r.affected_rows }} / {{ r.total_rows }}
- **Pass Rate:** {{ "%.2f"|format(r.pass_rate * 100) }}%
{% if r.threshold is not none %}- **Threshold:** {{ r.threshold }}{% endif %}
{% if r.measured_value is not none %}- **Measured Value:** {{ r.measured_value }}{% endif %}
{% if r.sql_used %}- **SQL:** `{{ r.sql_used }}`{% endif %}
{% if r.sample_violations %}
**Sample Violations:**

| Key | Value |
|-----|-------|
{% for v in r.sample_violations[:5] %}{% for k, val in v.items() %}| {{ k }} | {{ val }} |
{% endfor %}| --- | --- |
{% endfor %}
{% endif %}

---

{% endfor %}

## Dimension Breakdown

| Dimension | Checks | Passed | Failed |
|-----------|--------|--------|--------|
{% for dim, stats in dimensions.items() -%}
| {{ dim }} | {{ stats.total }} | {{ stats.passed }} | {{ stats.failed }} |
{% endfor %}

---

*Report generated by Financial Data Manager v1.4.0*
"""

# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Quality Report</title>
    <style>
        :root {
            --pass-color: #22c55e;
            --fail-color: #ef4444;
            --bg: #0f172a;
            --surface: #1e293b;
            --text: #e2e8f0;
            --muted: #94a3b8;
            --border: #334155;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: var(--bg);
            color: var(--text);
            padding: 2rem;
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
        h2 { font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
        h3 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
        .meta { color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }
        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.2rem;
            text-align: center;
        }
        .card .value { font-size: 2rem; font-weight: 700; }
        .card .label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; }
        .pass { color: var(--pass-color); }
        .fail { color: var(--fail-color); }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 1.5rem;
            font-size: 0.9rem;
        }
        th, td {
            padding: 0.6rem 0.8rem;
            border: 1px solid var(--border);
            text-align: left;
        }
        th { background: var(--surface); font-weight: 600; }
        tr:nth-child(even) { background: rgba(255,255,255,0.02); }
        .badge {
            display: inline-block;
            padding: 0.15rem 0.6rem;
            border-radius: 4px;
            font-size: 0.8rem;
            font-weight: 600;
        }
        .badge-pass { background: rgba(34,197,94,0.15); color: var(--pass-color); }
        .badge-fail { background: rgba(239,68,68,0.15); color: var(--fail-color); }
        .detail-block {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.2rem;
            margin-bottom: 1rem;
        }
        .detail-block p { margin: 0.3rem 0; }
        code { background: rgba(255,255,255,0.08); padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.85rem; }
        footer { margin-top: 3rem; color: var(--muted); font-size: 0.8rem; text-align: center; }
    </style>
</head>
<body>
<div class="container">
    <h1>Data Quality Report</h1>
    <div class="meta">
        Generated: {{ timestamp }} | Database: {{ db_path }}
    </div>

    <div class="summary-cards">
        <div class="card">
            <div class="value">{{ total }}</div>
            <div class="label">Total Checks</div>
        </div>
        <div class="card">
            <div class="value pass">{{ passed }}</div>
            <div class="label">Passed</div>
        </div>
        <div class="card">
            <div class="value fail">{{ failed }}</div>
            <div class="label">Failed</div>
        </div>
        <div class="card">
            <div class="value">{{ pass_rate }}%</div>
            <div class="label">Pass Rate</div>
        </div>
    </div>

    <h2>Check Summary</h2>
    <table>
        <thead>
            <tr>
                <th>#</th><th>Check ID</th><th>Dimension</th><th>Name</th>
                <th>Result</th><th>Affected</th><th>Total</th><th>Pass Rate</th>
            </tr>
        </thead>
        <tbody>
        {% for r in results %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ r.check_id }}</td>
                <td>{{ r.dimension }}</td>
                <td>{{ r.name }}</td>
                <td><span class="badge {{ 'badge-pass' if r.passed else 'badge-fail' }}">{{ "PASS" if r.passed else "FAIL" }}</span></td>
                <td>{{ r.affected_rows }}</td>
                <td>{{ r.total_rows }}</td>
                <td>{{ "%.2f"|format(r.pass_rate * 100) }}%</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2>Detailed Results</h2>
    {% for r in results %}
    <div class="detail-block">
        <h3>{{ r.check_id }}: {{ r.name }}
            <span class="badge {{ 'badge-pass' if r.passed else 'badge-fail' }}">{{ "PASS" if r.passed else "FAIL" }}</span>
        </h3>
        <p><strong>Dimension:</strong> {{ r.dimension }}</p>
        <p><strong>Description:</strong> {{ r.description }}</p>
        <p><strong>Details:</strong> {{ r.details }}</p>
        <p><strong>Affected Rows:</strong> {{ r.affected_rows }} / {{ r.total_rows }}</p>
        {% if r.sql_used %}<p><strong>SQL:</strong> <code>{{ r.sql_used }}</code></p>{% endif %}
        {% if r.sample_violations %}
        <p><strong>Sample Violations:</strong></p>
        <table>
            <thead><tr>{% for k in r.sample_violations[0].keys() %}<th>{{ k }}</th>{% endfor %}</tr></thead>
            <tbody>
            {% for v in r.sample_violations[:5] %}
                <tr>{% for val in v.values() %}<td>{{ val }}</td>{% endfor %}</tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
    {% endfor %}

    <h2>Dimension Breakdown</h2>
    <table>
        <thead><tr><th>Dimension</th><th>Checks</th><th>Passed</th><th>Failed</th></tr></thead>
        <tbody>
        {% for dim, stats in dimensions.items() %}
            <tr>
                <td>{{ dim }}</td>
                <td>{{ stats.total }}</td>
                <td class="pass">{{ stats.passed }}</td>
                <td class="{{ 'fail' if stats.failed > 0 else '' }}">{{ stats.failed }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <footer>Financial Data Manager v1.4.0</footer>
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------


def _build_context(results: list[DQResult], db_path: Optional[Path] = None) -> dict:
    """Build the template context dict from DQ results."""
    passed = sum(1 for r in results if r.passed)
    failed = len(results) - passed
    pass_rate = round(passed / len(results) * 100, 1) if results else 0.0

    # Dimension breakdown
    dimensions: dict[str, dict[str, int]] = {}
    for r in results:
        d = dimensions.setdefault(r.dimension, {"total": 0, "passed": 0, "failed": 0})
        d["total"] += 1
        if r.passed:
            d["passed"] += 1
        else:
            d["failed"] += 1

    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "db_path": str(db_path or "default"),
        "total": len(results),
        "passed": passed,
        "failed": failed,
        "pass_rate": pass_rate,
        "results": results,
        "dimensions": dimensions,
    }


def generate_markdown_report(
    results: list[DQResult],
    output_path: Optional[Path] = None,
    db_path: Optional[Path] = None,
) -> Path:
    """
    Render a Markdown DQ report and write it to disk.

    Returns the output file path.
    """
    ensure_dirs()
    ctx = _build_context(results, db_path)
    rendered = Template(_MD_TEMPLATE).render(**ctx)

    out = output_path or (REPORT_DIR / "dq_report.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    return out


def generate_html_report(
    results: list[DQResult],
    output_path: Optional[Path] = None,
    db_path: Optional[Path] = None,
) -> Path:
    """
    Render an HTML DQ report and write it to disk.

    Returns the output file path.
    """
    ensure_dirs()
    ctx = _build_context(results, db_path)
    rendered = Template(_HTML_TEMPLATE).render(**ctx)

    out = output_path or (REPORT_DIR / "dq_report.html")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    return out


def generate_reports(
    results: list[DQResult],
    db_path: Optional[Path] = None,
) -> tuple[Path, Path]:
    """Generate both Markdown and HTML reports, returning their paths."""
    md = generate_markdown_report(results, db_path=db_path)
    html = generate_html_report(results, db_path=db_path)
    return md, html
