"""
Crypto Wallet Explorer
======================

A professional blockchain education toolkit for understanding cryptocurrency
wallets, key derivation, transaction construction, and blockchain exploration.

Modules
-------
wallet_generator
    BIP-39 mnemonic generation, BIP-32/44 key derivation, Ethereum address computation.
key_visualizer
    Rich terminal visualization of the hierarchical key derivation path.
transaction_builder
    Raw Ethereum transaction construction and signing for testnet use.
transaction_explorer
    Etherscan API integration for fetching and decoding transaction details.
block_explorer
    Block-level data fetching and transaction listing.
balance_checker
    ETH and ERC-20 token balance queries.
cli
    Click-based command-line interface for all features.
utils
    Hex encoding, address validation, unit conversions, and shared helpers.

.. warning::
    EDUCATIONAL USE ONLY -- TESTNET ONLY.
    Never use wallets or keys generated by this tool for real cryptocurrency.
    All generated material should be considered publicly compromised.
"""

__version__ = "1.0.0"
__project__ = "Crypto Wallet Explorer"

# Security banner printed on import to reinforce testnet-only usage
import sys as _sys

_SECURITY_BANNER = (
    "\n"
    "=" * 72 + "\n"
    "  WARNING: Crypto Wallet Explorer -- EDUCATIONAL / TESTNET USE ONLY\n"
    "  Do NOT use generated wallets, keys, or addresses for real funds.\n"
    "  All generated cryptographic material is INSECURE by design.\n"
    "=" * 72 + "\n"
)

# Only print banner when running interactively (not during testing)
if hasattr(_sys, "ps1") or "click" in _sys.modules:
    print(_SECURITY_BANNER, file=_sys.stderr)
